jenkins:
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${USER_NAME}
          password: ${USER_PASSWORD}
  slaveAgentPort: 50000
  agentProtocols:
    - JNLP4-connect
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
    - ecs:
        credentialsId: ''
        cluster: ${ECS_CLUSTER_ARN}
        name: ${ECS_CLUSTER_NAME}
        regionName: ${ECS_REGION}
        jenkinsUrl: ${JENKINS_URL}
        tunnel: ${JENKINS_CONTROLLER_AGENT_TUNNEL}
        templates:
          - assignPublicIp: false
            cpu: 1024
            executionRole: ${ECS_EXECUTION_ROLE_ARN}
            taskrole: ${ECS_AGENT_TASK_ROLE_ARN}
            image: ${JENKINS_AGENT_IMAGE}
            label: "agent"
            templateName: "agent"
            launchType: "FARGATE"
            logDriver: "awslogs"
            logDriverOptions:
              - name: awslogs-group
                value: ${JENKINS_AGENT_CLOUDWATCH_LOG_GROUP_NAME}
              - name: awslogs-region
                value: ${JENKINS_AGENT_CLOUDWATCH_LOG_GROUP_REGION}
              - name: awslogs-stream-prefix
                value: jenkins-agent
            memoryReservation: 2048
            networkMode: "awsvpc"
            operatingSystemFamily: "LINUX"
            platformVersion: "LATEST"
            privileged: false
            remoteFSRoot: "/home/jenkins"
            securityGroups: ${JENKINS_AGENT_SECURITY_GROUP}
            subnets: ${JENKINS_AGENT_SUBNET_IDS}